project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    logo: Images/Logos_Icons/main_logo3.png
    left:
      - href: Pages/calendar.qmd
        text: Calendar
      - href: Pages/projects.qmd
        text: Projects
      - href: Pages/meetings.qmd
        text: Meetings
      - href: Pages/blog.qmd
        text: Blog
      - sidebar:about
      - href: Pages/schedule.qmd
        text: Schedule Meeting
  sidebar:
    - title: "Meetings"
      style: "docked"
      collapse-level: 2
      contents:
        - Pages/meetings.qmd
        - Pages/past.qmd
        
    - title: "Projects"
      style: "docked"
      collapse-level: 2
      contents:
        - Pages/projects.qmd
        - Pages/projects2223.qmd
    - id: about
      title: "About"
      contents:
        - Pages/about.qmd
        - Pages/officers.qmd

  favicon: "Images/Logos_Icons/main_logo3.png"
  page-footer: "Site Originally Designed by Ethan Marzban using Quarto; Â©2023"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
