project:
  type: website
  output-dir: docs
  resources:
    - Files/**
    - Images/**

website:
  google-analytics: "G-PBFWYVSBYV"
  title: ""
  navbar:
    logo: Images/Logos_Icons/main_logo3.png
    left:
      - href: Pages/calendar.qmd
        text: Calendar
      - href: Pages/projects2425.qmd
        text: Projects
      - href: Pages/meetings2526.qmd
        text: Meetings
      - href: Pages/blog2526.qmd
        text: Blog
      - href: Pages/officers.qmd
        text: Officers
      - href: Pages/about.qmd
        text: About
        
  sidebar:
    - title: "Meetings"
      style: "docked"
      collapse-level: 2
      contents:
        - Pages/meetings2526.qmd
        - Pages/meetings2425.qmd
        - Pages/meetings.qmd
        - Pages/past.qmd

    - title: "Blog"
      style: "docked"
      collapse-level: 2
      contents:
        - Pages/blog2526.qmd
        - Pages/blog2425.qmd

    - title: "Projects"
      style: "docked"
      collapse-level: 2
      contents:
        - Pages/projects2425.qmd
        - Pages/projects2324.qmd
        - Pages/projects2223.qmd

  favicon: "Images/Logos_Icons/main_logo3.png"
  page-footer: "Site Originally Designed by Ethan Marzban using Quarto; Â©2023"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
